"""
src/encoders/grounded_sam_encoder.py
------------------------------------
Grounded-SAM conditioning support for the LoRAdapter segmentation pipeline.

WHAT THIS BRANCH DOES DIFFERENTLY FROM THE SegFormer PIPELINE:
  The SegFormer pipeline (src/encoders/seg_encoder.py) is LOCKED to 19 Cityscapes
  classes with a fixed hand-picked palette. Grounded-SAM instead produces maps
  from an OPEN, user-defined class set (whatever prompts were given to
  GroundingDINO when the maps were generated). So the two things Cityscapes
  hard-codes — the class COUNT and the COLOUR per class — must here be data,
  loaded from a class-definition file the user fills in once they know their
  exact class order.

WHAT IS AND ISN'T BUILT HERE (Tier 1 — training on pre-saved maps):
  You already have (raw_image, seg_map) pairs generated by Grounded-SAM offline.
  Training reads those saved maps directly (skip_encode=True in grounded_sam_training.py —
  the encoder's forward() is NEVER called during the training loss step). So
  Tier 1 needs only:
    • a palette sized to your class set (load_grounded_sam_palette below), and
    • an nn.Module to occupy the encoder slot so accelerate can .prepare() it.
  It does NOT need a live GroundingDINO+SAM running. GroundedSamEncoder below is
  therefore a LIGHTWEIGHT slot-filler: it constructs with zero heavy deps and
  raises a clear, actionable error if forward()/label_ids() is ever called
  (i.e. if you try live inference on a brand-new image, or enable the mIoU
  metric). Building that live path is Tier 2 — a separate, heavier job needing
  the groundingdino + segment-anything packages, their checkpoints, and your
  real class-name prompts.

  The `live_available = False` attribute is how grounded_sam_training.py knows to SKIP the
  mIoU controllability metric for this encoder (that metric segments the
  GENERATED image, which would require the live models). PSNR/SSIM and the
  monitoring grids do not need a live segmenter and stay on.

SHARED MATH: colourising a class-ID map and inverting it back are identical
  operations regardless of taxonomy, so we REUSE seg_palette_tensor /
  seg_colorize_ids / seg_ids_from_colormap from seg_encoder.py rather than
  duplicating them. Only the palette CONTENTS differ.
"""

import colorsys
import json
from pathlib import Path

from torch import nn


# ============================================================================ #
#  CLASS-DEFINITION FILE  ->  (names, palette)                                  #
# ============================================================================ #
#
# The class-definition file is a JSON object keyed by class-ID STRING, in the
# exact ID order your Grounded-SAM maps use (pixel value i == class i). Two
# accepted value forms, and you can mix them per entry:
#
#   Names only (colours auto-generated — recommended; colours don't affect
#   correctness, only that each class is visually distinct):
#     {
#       "0": "road",
#       "1": "sidewalk",
#       "2": "building",
#       "3": "car"
#     }
#
#   Name + explicit colour (use only if you want a specific look):
#     {
#       "0": {"name": "road",     "color": [128, 64, 128]},
#       "1": {"name": "sidewalk", "color": [244, 35, 232]}
#     }
#
# IDs MUST be contiguous 0..N-1 with no gaps — a gap means the palette and the
# on-disk pixel values would silently disagree. This is validated below.


def generate_distinct_palette(num_classes: int) -> list[tuple[int, int, int]]:
    """
    Deterministically generate `num_classes` well-separated RGB colours.

    WHY deterministic + well-separated: the LoRA mapper is a Conv2d that reads
    the colour map as its conditioning signal. Classes that share similar
    colours are harder for it to tell apart, which is exactly why the Cityscapes
    palette was hand-picked to spread classes across colour space. We reproduce
    that property automatically by walking the HUE circle in golden-ratio steps
    (maximally spreads N hues no matter what N is) at full saturation/value.
    Deterministic (no RNG) so the same class count always yields the same
    palette — training and any later inference stay pixel-identical.

    Returns a list of (R, G, B) ints in 0..255, length == num_classes.
    """
    golden_ratio_conjugate = 0.618033988749895   # spreads successive hues evenly
    palette: list[tuple[int, int, int]] = []
    hue = 0.0
    for _ in range(num_classes):
        # Full saturation + value -> vivid, easy-to-separate colours.
        r, g, b = colorsys.hsv_to_rgb(hue, 0.85, 0.95)
        palette.append((int(r * 255), int(g * 255), int(b * 255)))
        hue = (hue + golden_ratio_conjugate) % 1.0
    return palette


def load_grounded_sam_palette(
    classes_file: str | Path,
) -> tuple[list[str], list[tuple[int, int, int]]]:
    """
    Load the class-definition JSON and return (class_names, palette).

    class_names : list[str] indexed by class id (names[i] is class i's name).
    palette     : list[(R,G,B)] indexed by class id, length == number of classes.

    Any entry that does not specify an explicit "color" gets a colour from
    generate_distinct_palette() for the full class count, so the auto-generated
    colours stay mutually well-separated even when only some classes are
    hand-coloured.

    Fails loudly (ValueError) if the IDs are not a contiguous 0..N-1 range —
    silent gaps here would desynchronise the palette from the on-disk pixel
    values, the single worst class of bug in this project.
    """
    classes_file = Path(classes_file)
    with open(classes_file, "r", encoding="utf-8") as f:
        raw = json.load(f)

    # Ignore meta keys (anything starting with "_", e.g. "__README__") so the
    # template's documentation key doesn't get parsed as a class id.
    raw = {k: v for k, v in raw.items() if not str(k).startswith("_")}
    if not raw:
        raise ValueError(f"{classes_file}: no class entries found (only meta keys?).")

    # Parse and sort by integer id so list index == class id.
    try:
        ids = sorted(int(k) for k in raw.keys())
    except ValueError as e:
        raise ValueError(
            f"{classes_file}: every key must be an integer class id string "
            f"(e.g. \"0\", \"1\"). Got a non-integer key."
        ) from e

    expected = list(range(len(ids)))
    if ids != expected:
        raise ValueError(
            f"{classes_file}: class ids must be contiguous 0..N-1 with no gaps. "
            f"Expected {expected}, got {ids}. A gap means the palette and your "
            f"seg-map pixel values would disagree."
        )

    n = len(ids)
    auto = generate_distinct_palette(n)   # fallback colours, well-separated for N

    names: list[str] = []
    palette: list[tuple[int, int, int]] = []
    for i in ids:
        entry = raw[str(i)]
        if isinstance(entry, str):
            names.append(entry)
            palette.append(auto[i])
        elif isinstance(entry, dict):
            names.append(entry.get("name", f"class_{i}"))
            color = entry.get("color")
            if color is None:
                palette.append(auto[i])
            else:
                if (not isinstance(color, (list, tuple)) or len(color) != 3):
                    raise ValueError(
                        f"{classes_file}: class {i} 'color' must be [R,G,B]; got {color!r}."
                    )
                palette.append((int(color[0]), int(color[1]), int(color[2])))
        else:
            raise ValueError(
                f"{classes_file}: class {i} value must be a name string or a "
                f"{{'name':..., 'color':[R,G,B]}} object; got {type(entry).__name__}."
            )

    return names, palette


# ============================================================================ #
#  ENCODER SLOT MODULE (Tier 1 — training only)                                 #
# ============================================================================ #

class GroundedSamEncoder(nn.Module):
    """
    Lightweight encoder-slot module for TRAINING on pre-saved Grounded-SAM maps.

    Occupies the same `lora.struct.encoder` slot the SegFormer SegmentationEncoder
    does, and is an nn.Module so accelerate's .prepare()/.to()/.eval() treat it
    identically. It holds ONLY configuration (size, palette, class count) — it
    deliberately does NOT load GroundingDINO or SAM, so training (which never
    calls forward(): skip_encode=True) needs none of those heavy dependencies.

    ENCODER-SLOT CONTRACT it would satisfy IF live (see seg_encoder.py for the
    full contract): input [B,3,H,W] in [-1,1] -> output colour map [B,3,size,size]
    in [0,1]. That live behaviour is Tier 2 and is intentionally not implemented
    here; forward()/label_ids() raise a clear error rather than silently
    returning wrong data.

    live_available = False tells grounded_sam_training.py to skip the mIoU metric (which
    needs to segment the generated image live). All other monitoring works.

    Args:
      size         : final square side of the conditioning map (== cfg.size).
      num_classes  : number of Grounded-SAM classes (== len(palette)); stored so
                     downstream code can size things without re-reading the file.
      palette      : class-id -> (R,G,B) list, from load_grounded_sam_palette().
    """

    live_available: bool = False   # read by grounded_sam_training.py to gate the mIoU metric

    def __init__(
        self,
        size: int,
        num_classes: int | None = None,
        palette: list[tuple[int, int, int]] | None = None,
    ) -> None:
        super().__init__()
        self.size = size
        self.palette = palette
        self.num_classes = num_classes if num_classes is not None else (
            len(palette) if palette is not None else None
        )

    def _not_live(self, what: str):
        return NotImplementedError(
            f"GroundedSamEncoder.{what}() is not implemented on this branch. "
            f"This encoder is the TRAINING-ONLY slot filler (Tier 1): training "
            f"reads pre-saved Grounded-SAM maps via skip_encode=True and never "
            f"calls the encoder. Live map generation (needed for inference on a "
            f"NEW image, or the mIoU metric) is Tier 2 — it requires the "
            f"GroundingDINO + segment-anything packages, their checkpoints, and "
            f"your class-name prompts, none of which are wired up yet."
        )

    def forward(self, imgs):
        # Would run live Grounded-SAM at inference. Not built (Tier 2).
        raise self._not_live("forward")

    def label_ids(self, imgs):
        # Would segment an image to raw class-IDs (used by the mIoU metric). Not built.
        raise self._not_live("label_ids")
